name: Build Android Apk on Release

on:
  release:
    types: [published]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Bump App version
        run: |
         chmod +x ./bump_version.sh
         ./bump_version.sh ${{ github.event.release.tag_name }}
        shell: bash
      - name: Decode Keystore
        env:
            ENCODED_STRING: ${{ secrets.KEYSTORE }}
        run: |
            TMP_KEYSTORE_FILE_PATH=app/keystore
            mkdir "${TMP_KEYSTORE_FILE_PATH}"
            echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/github-keystore.jks
      - name: Build APK
        run: bash ./gradlew app:assembleRelease --stacktrace
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        
      - name: Rename APK
        run: |
          mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/comick-${{ github.event.release.tag_name }}.apk 
      - name: Release APK
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/comick-${{ github.event.release.tag_name }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit bumped version
        run: |
          git config --global user.name "Release Runner"
          git add --force ./app/build.gradle
          git commit -am "Bump release version"
          git tag -fa ${{ github.event.release.tag_name }} -m "Bump to version ${{ github.event.release.tag_name }}"
          git push origin HEAD:master --tags --force
