name: Build Android Apk on Release

on:
  release:
    types: [published]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Rename APK
        run: |
          mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/comick.apk 
      - name: Release APK
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/debug/comick.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
